(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const C = { grid:'#dce5f2', ink:'#10213e', blue:'#2458d6', orange:'#f05a1a', muted:'#52627a' };
  function drawPlane(canvas, draw) {
    const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height,p=42,u=Math.min((w-p*2)/10,(h-p*2)/10);
    const X=x=>w/2+x*u,Y=y=>h/2-y*u;
    ctx.clearRect(0,0,w,h);ctx.strokeStyle=C.grid;ctx.lineWidth=1;
    for(let n=-5;n<=5;n++){ctx.beginPath();ctx.moveTo(X(n),p/2);ctx.lineTo(X(n),h-p/2);ctx.stroke();ctx.beginPath();ctx.moveTo(p/2,Y(n));ctx.lineTo(w-p/2,Y(n));ctx.stroke();}
    ctx.strokeStyle=C.ink;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(p/2,Y(0));ctx.lineTo(w-p/2,Y(0));ctx.moveTo(X(0),h-p/2);ctx.lineTo(X(0),p/2);ctx.stroke();
    ctx.fillStyle=C.muted;ctx.font='13px Arial';for(let n=-5;n<=5;n++)if(n){ctx.fillText(n,X(n)-4,Y(0)+18);ctx.fillText(n,X(0)-20,Y(n)+4)}ctx.fillStyle=C.ink;ctx.font='bold 16px Arial';ctx.fillText('x',w-p+8,Y(0)+5);ctx.fillText('y',X(0)+8,p/2);draw(ctx,X,Y);
  }
  function dot(ctx,X,Y,x,y,label,color=C.orange){ctx.fillStyle=color;ctx.beginPath();ctx.arc(X(x),Y(y),7,0,Math.PI*2);ctx.fill();ctx.fillStyle=C.ink;ctx.font='bold 14px Arial';ctx.fillText(label,X(x)+10,Y(y)-10)}
  function hero(){drawPlane($('heroCanvas'),(ctx,X,Y)=>{const pts=[[-4,-3,'Casa'],[-2,1,''],[1,0,''],[4,3,'Destino']];ctx.strokeStyle=C.blue;ctx.lineWidth=4;ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(X(p[0]),Y(p[1])):ctx.moveTo(X(p[0]),Y(p[1])));ctx.stroke();pts.forEach(p=>dot(ctx,X,Y,p[0],p[1],p[2]?`${p[2]} (${p[0]}, ${p[1]})`:`(${p[0]}, ${p[1]})`))})}
  let px=3,py=2;
  function point(){drawPlane($('pointCanvas'),(ctx,X,Y)=>{ctx.setLineDash([5,5]);ctx.strokeStyle=C.blue;ctx.beginPath();ctx.moveTo(X(px),Y(py));ctx.lineTo(X(px),Y(0));ctx.moveTo(X(px),Y(py));ctx.lineTo(X(0),Y(py));ctx.stroke();ctx.setLineDash([]);dot(ctx,X,Y,px,py,`P (${px}, ${py})`)});$('xOutput').textContent=px;$('yOutput').textContent=py;$('pointFeedback').textContent=`P está ${Math.abs(px)} unidades ${px>=0?'a la derecha':'a la izquierda'} y ${Math.abs(py)} unidades ${py>=0?'por encima':'por debajo'} del origen.`}
  const val=v=>Math.max(-5,Math.min(5,Number(v)||0));
  function distance(){const a={x:val($('ax').value),y:val($('ay').value)},b={x:val($('bx').value),y:val($('by').value)},dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy);drawPlane($('distanceCanvas'),(ctx,X,Y)=>{ctx.setLineDash([6,5]);ctx.strokeStyle=C.muted;ctx.beginPath();ctx.moveTo(X(a.x),Y(a.y));ctx.lineTo(X(b.x),Y(a.y));ctx.lineTo(X(b.x),Y(b.y));ctx.stroke();ctx.setLineDash([]);ctx.strokeStyle=C.blue;ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(X(a.x),Y(a.y));ctx.lineTo(X(b.x),Y(b.y));ctx.stroke();dot(ctx,X,Y,a.x,a.y,`A (${a.x}, ${a.y})`);dot(ctx,X,Y,b.x,b.y,`B (${b.x}, ${b.y})`,C.blue)});$('distanceFeedback').textContent=`Δx = ${dx}, Δy = ${dy}. Distancia: √(${dx*dx} + ${dy*dy}) = ${d.toFixed(2)} unidades.`}
  const conics={circle:['Circunferencia','Todos sus puntos están a la misma distancia del centro. Aparece en ruedas, relojes y cúpulas.','(x − h)² + (y − k)² = r²'],parabola:['Parábola','Una trayectoria parabólica aparece al lanzar un objeto y en las antenas parabólicas.','y = ax²'],ellipse:['Elipse','La suma de las distancias a dos focos es constante. Los planetas describen órbitas elípticas.','x²/a² + y²/b² = 1'],hyperbola:['Hipérbola','La diferencia de las distancias a dos focos es constante. Se utiliza en navegación.','x²/a² − y²/b² = 1']};let conic='circle';
  function conicDraw(){drawPlane($('conicCanvas'),(ctx,X,Y)=>{ctx.strokeStyle=C.blue;ctx.lineWidth=3;if(conic==='hyperbola'){[-1,1].forEach(side=>{ctx.beginPath();for(let t=-2;t<=2;t+=.03){const x=side*1.25*Math.cosh(t),y=1.25*Math.sinh(t);if(t<=-1.97)ctx.moveTo(X(x),Y(y));else ctx.lineTo(X(x),Y(y))}ctx.stroke()});return}ctx.beginPath();for(let t=-5;t<=5;t+=.04){let x=t,y;if(conic==='circle'){x=3*Math.cos(t);y=3*Math.sin(t)}else if(conic==='parabola')y=.22*t*t-2.5;else{x=4*Math.cos(t);y=2*Math.sin(t)}if(t<=-4.96)ctx.moveTo(X(x),Y(y));else ctx.lineTo(X(x),Y(y))}ctx.stroke()});const d=conics[conic];$('conicTitle').textContent=d[0];$('conicText').textContent=d[1];$('conicFormula').textContent=d[2]}
  const Q=[['¿Qué indica el primer número de (3, 4)?',['Movimiento horizontal','Movimiento vertical','La distancia'],0],['¿Dónde está (−2, 5)?',['Cuadrante I','Cuadrante II','Cuadrante III'],1],['¿Qué mide la fórmula de la distancia?',['La separación entre dos puntos','La inclinación','El radio'],0],['El punto medio sirve para…',['Encontrar una posición equidistante','Calcular un área','Dibujar una curva'],0],['Una pendiente positiva significa que la recta…',['Sube','Baja','Es horizontal'],0],['¿Qué curva modela un lanzamiento?',['Parábola','Hipérbola','Circunferencia'],0],['Los planetas siguen una…',['Elipse','Recta','Parábola'],0],['Una rueda se aproxima a una…',['Circunferencia','Hipérbola','Recta'],0],['En (0, 0) se encuentra…',['El origen','El foco','El radio'],0],['Si x es negativa, el punto queda a la…',['Izquierda','Derecha','Arriba'],0],['Si y es positiva, el punto queda…',['Arriba','Abajo','En el eje Y'],0],['La pendiente mide…',['Inclinación','Área','Radio'],0],['GPS utiliza principalmente…',['Coordenadas','Colores','Ángulos rectos'],0],['Una antena parabólica concentra señales en…',['El foco','El origen','El eje X'],0],['El sistema Loran se relaciona con…',['Hipérbolas','Cuadrados','Triángulos equiláteros'],0]];let qi=0,score=0,answered=false;
  function quiz(){const q=Q[qi];$('quizStatus').textContent=`Pregunta ${qi+1} de ${Q.length}`;$('quizProgress').style.width=`${qi/Q.length*100}%`;$('quizQuestion').textContent=q[0];$('quizFeedback').textContent='';$('nextQuestion').disabled=true;answered=false;$('quizAnswers').replaceChildren();q[1].forEach((text,i)=>{const b=document.createElement('button');b.className='answer';b.textContent=text;b.addEventListener('click',()=>{if(answered)return;answered=true;const ok=i===q[2];b.classList.add(ok?'correct':'wrong');if(ok){score++;$('quizFeedback').textContent='Correcto. Buen razonamiento.'}else $('quizFeedback').textContent=`La respuesta correcta es «${q[1][q[2]]}».`;$('nextQuestion').disabled=false});$('quizAnswers').append(b)})}
  function init(){hero();point();distance();conicDraw();quiz();$('menuButton').onclick=()=>{const n=$('mainNav');n.classList.toggle('open');$('menuButton').setAttribute('aria-expanded',n.classList.contains('open'))};$('xInput').oninput=e=>{px=Number(e.target.value);point()};$('yInput').oninput=e=>{py=Number(e.target.value);point()};$('pointCanvas').onclick=e=>{const r=e.currentTarget.getBoundingClientRect();px=Math.round((e.clientX-r.left)/r.width*10-5);py=Math.round(5-(e.clientY-r.top)/r.height*10);$('xInput').value=px;$('yInput').value=py;point()};['ax','ay','bx','by'].forEach(id=>$(id).oninput=distance);document.querySelectorAll('[data-conic]').forEach(b=>b.onclick=()=>{conic=b.dataset.conic;document.querySelectorAll('[data-conic]').forEach(x=>x.classList.toggle('selected',x===b));conicDraw()});$('nextQuestion').onclick=()=>{qi++;if(qi<Q.length)quiz();else{$('quizCard').hidden=true;$('quizProgress').style.width='100%';$('quizResult').hidden=false;$('resultText').textContent=`Has acertado ${score} de ${Q.length} preguntas (${Math.round(score/Q.length*100)} %).`}};$('restartButton').onclick=()=>{qi=0;score=0;$('quizCard').hidden=false;$('quizResult').hidden=true;quiz()};$('printButton').onclick=()=>window.print()}
  window.addEventListener('DOMContentLoaded',init);
})();
